#!/bin/sh

# Makes links such that the source tree may be used as a distribution
# root (via STADENROOT). This avoids needing to do make dist or make
# install.

# Lib tcl files. Point to src.
cd lib
ln -s ../src/copy_reads .
ln -s ../src/gap4 ./gap
ln -s ../src/prefinish .
ln -s ../src/pregap4 .
ln -s ../src/seqed .
ln -s ../src/spin .
ln -s ../src/spin2 .
ln -s ../src/spin2_emboss .
ln -s ../src/spin_emboss .
ln -s ../src/tk_utils .
ln -s ../src/trev .
ln -s ../src/haplo .
cd ..

# Binary links to allow running of programs within the source tree without
# the need to explicitly build a distribution or do a make install
for i in alpha linux solaris sgi macosx linux-x86_64 linux-ia64
do
	# Run-time libraries
	cd lib
	ln -s ../src/lib/$i-binaries .
	cd ..

	# Programs
	mkdir $i-bin
	cd $i-bin
	ln -s ../src/eba/$i-binaries/eba .
	ln -s ../src/find_renz/$i-binaries/find_renz .
	ln -s ../src/abi/$i-binaries/getABISampleName .
	ln -s ../src/abi/$i-binaries/getABIcomment .
	ln -s ../src/abi/$i-binaries/getABIdate .
	ln -s ../src/abi/$i-binaries/getABIhex .
	ln -s ../src/abi/$i-binaries/getABIraw .
	ln -s ../src/abi/$i-binaries/getABIstring .
	ln -s ../src/get_scf_field/$i-binaries/get_scf_field .
	ln -s ../src/hetins/$i-binaries/hetins .
	ln -s ../src/init_exp/$i-binaries/init_exp .
	ln -s ../src/make_weights/$i-binaries/make_weights .
	ln -s ../src/mutscan/$i-binaries/mutscan .
	ln -s ../src/polyA_clip/$i-binaries/polyA_clip .
	ln -s ../src/qclip/$i-binaries/qclip .
	ln -s ../src/io_lib/progs/$i-binaries/convert_trace .
	ln -s ../src/io_lib/progs/$i-binaries/extract_seq .
	ln -s ../src/io_lib/progs/$i-binaries/index_tar .
	ln -s ../src/io_lib/progs/$i-binaries/makeSCF .
	ln -s ../src/io_lib/progs/$i-binaries/scf_dump .
	ln -s ../src/io_lib/progs/$i-binaries/scf_info .
	ln -s ../src/io_lib/progs/$i-binaries/scf_update .
	ln -s ../src/io_lib/progs/$i-binaries/trace_dump .
	ln -s ../src/screen_seq/$i-binaries/screen_seq .
	ln -s ../src/tk_utils/$i-binaries/stash .
	ln -s ../src/tracediff/$i-binaries/tracediff .
	ln -s ../src/vector_clip/$i-binaries/vector_clip .

	# These need to be copied or the find_dir function follows the
	# symbolic link and identifies STADENROOT wrongly.
	cp ../src/gap4/gap4 .
	cp ../src/prefinish/prefinish .
	cp ../src/pregap4/pregap4 .
	cp ../src/spin/spin .
	cp ../src/trev/trev .
	cd ..
done

# Other links which we'd normally be happy with, but we cannot put
# symlinks in CVS.
ln -s doc/manual .
ln -s doc/manual/man .
cd doc/scripting_manual
ln -s ../manual/tools .
cd ..

