#!/bin/sh
if [ $# -eq 0 ]
then
    echo "Usage: gzip_trace file1 ..."
    echo "eg, 'gzip_trace *.scf'"
    exit
fi

for i in ${@+"$@"}
do
    echo "Compressing $i"
    CheckIfZipped=`gzip -lv "$i" 2>&1 | egrep '^defla'`

    if [ -n  "$CheckIfZipped"  ]
    then
        echo $i is already zipped ... skipping
    else
        gzip -v < "$i" > .tmp && mv .tmp "$i"
    fi

done
