#!/bin/sh

# For all the gifs that are split into a small and large version, create a
# .gif.html file which is simply an html page containing the gif. This is
# needed because the tcl/tk html viewer doesn't support gif files directly.

for i in *.small.*.gif
do
    name=`echo $i | sed 's/\.small\.\(.*\)\.gif$/\.\1/'`
    # name=`echo $i | sed 's/.small.gif$//'`
    echo "Creating $name.gif.html"
    cat > $name.gif.html << _eof_
<html><body bgcolor="#ffffff">
<img src="$name.gif">
</body></html>
_eof_
done