#!/usr/bin/perl -w

#
# Converts a png image to postscript with the following rules.
#
# 1. The standard conversion is at 120x120 dpi.
# 2. The maximum width is 16.3 cm.
#
# We resolve rule 2 by increasing the dpi.
#

# Location of imagic conversion program
#$convert = '/usr/local/bin/convert';
#$convert = '/usr/X11R6/bin/convert';
$convert = '/usr/bin/convert';

# Default density
$default_density = '120';

# For images with a non standard density, we list them here.
%densities = (
	      'conf_values_p', '124',
	      'consistency_p', '123',
	      'contig_editor.join', '168',
	      'contig_editor.screen', '168',
	      'contig_editor.traces', '161',
	      'contig_editor.traces.compact', '161',
	      'contig_editor_grey_scale', '168',
	      'contig_editor_mutations', '168',
	      'interface.menus', '26',
	      'primer_pos_plot', '126',
	      'primer_pos_seq_display', '131',
	      'read_coverage_p', '123',
	      'readpair_coverage_p', '125',
	      'restrict_enzymes', '126',
	      'spin_plot_base_comp_p', '121',
	      'spin_plot_drag1', '125',
	      'spin_plot_drag2', '125',
	      'spin_plot_drag3', '125',
	      'spin_restrict_enzymes_p', '125',
	      'spin_restrict_enzymes_p1', '125',
	      'spin_seq_display', '151',
	      'spin_sequence_display_t', '155',
	      'spin_trna_p', '121',
	      'stops', '128',
	      'traces_diff', '163',
	      'conf_values_p', '121',
	      'mut_contig_editor5', '167',
	      'mut_contig_editor_dis5', '167',
	      'mut_traces_het', '161',
	      'mut_traces_point', '161',
	      'mut_traces_positive', '161',
	      );

while ($#ARGV >= 0) {
    $_ = shift(@ARGV);
    next if (/\.small\./);
    s/\.png//;
    $fname = $_;
    $density = $densities{$_} ? $densities{$_} : $default_density;
    $density = $density . 'x' . $density;

    # Convert the image
    system "$convert -density $density $_.png $_.pdf";

    # Find the size of the postscript image.
    open(FILE, "$_.pdf") || die "Cannot open $_.pdf\n";
    binmode(FILE,":raw");
    while (<FILE>) {
	if (/^\/CropBox/) {
	    ($a,$b)=/^\/CropBox \[(\d+) \d+ (\d+) \d+\]/;
	    $width = $b-$a;
	}
    }
    close(FILE);

    # Check the size. 16.3cm = 462 1/72th inch.
    if ($width > 462) {
	$size=int($width/462.0*120+1);
	print "FIX: Suggested new density: '$fname', '$size',\n";
    }
}
