.TH "get_comment" 1 "" "" "Staden Package"
.SH "NAME"
.PP
get_comment \- extract comments from trace files

.SH "SYNOPSIS"
.PP

\fBget_comment\fP [ \fB-c\fP ] [ \fBField-ID\fP ... ]

.SH "DESCRIPTION"
.PP

The \fBget_comment\fP command extracts text fields from a variety of trace
formats, read in from stdin. Each comment is of the form
\fIField-ID\fP=\fIcomment\fP, regardless of the file format. \fIField-ID\fP is
typically 4 character identifier.

With no \fIField-ID\fP arguments specified all comments are listed. Otherwise
only those specified on the command line are listed.

.SH "OPTIONS"
.PP

.TP
\fB-h\fP
Display the usage help.

.TP
\fB-c\fP
Suppresses the output of the \fIField-ID\fP. Only the right hand side of the
comment is displayed. The default action is the display the full comment in
the form listed above.

.TE
.SH "SEE ALSO"
.PP

\fBget_scf_field\fR(1)
