SRCROOT=$(SRC)/..
include $(SRCROOT)/global.mk
include ../system.mk

all:
install:
clean:
spotless:
relink:
depend:

distsrc: distsrc_dirs
	cp $(S)/Copyright $(S)/README $(S)/README.jkb $(S)/example \
	   $(S)/example.int $(S)/example.for $(S)/example.rev $(S)/Makefile \
	   $(DIRNAME)
