SRCROOT=..
include	 $(SRCROOT)/mk/global.mk
include $(SRCROOT)/mk/$(MACHINE).mk

all:
install:
clean:
spotless:
relink:
depend:

distsrc: distsrc_dirs
	-cp -R Copyright README README.jkb example example.int example.for \
	       example.rev test Makefile $(DIRNAME)
