SRCROOT=$(SRC)/..
include $(SRCROOT)/global.mk
include ../system.mk

all:
install:
clean:
spotless:
relink:
depend:

distsrc: distsrc_dirs
	-cp -R Copyright README README.jkb example example.int example.for \
	       example.rev test Makefile $(DIRNAME)
