# Makefile.in generated automatically by automake 1.5 from Makefile.am.

# Copyright 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001
# Free Software Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.



SHELL = /bin/ksh

srcdir = .
top_srcdir = ..

prefix = /usr/local
exec_prefix = ${prefix}

bindir = ${exec_prefix}/bin
sbindir = ${exec_prefix}/sbin
libexecdir = ${exec_prefix}/libexec
datadir = ${prefix}/share
sysconfdir = ${prefix}/etc
sharedstatedir = ${prefix}/com
localstatedir = ${prefix}/var
libdir = ${exec_prefix}/lib
infodir = ${prefix}/info
mandir = ${prefix}/man
includedir = ${prefix}/include
oldincludedir = /usr/include
pkgdatadir = $(datadir)/io_lib
pkglibdir = $(libdir)/io_lib
pkgincludedir = $(includedir)/io_lib
top_builddir = ..

ACLOCAL = ${SHELL} /nfs/team71/psg/jkb/tmp/staden/src/io_lib/missing --run aclocal
AUTOCONF = ${SHELL} /nfs/team71/psg/jkb/tmp/staden/src/io_lib/missing --run autoconf
AUTOMAKE = ${SHELL} /nfs/team71/psg/jkb/tmp/staden/src/io_lib/missing --run automake
AUTOHEADER = ${SHELL} /nfs/team71/psg/jkb/tmp/staden/src/io_lib/missing --run autoheader

INSTALL = .././install-sh -c
INSTALL_PROGRAM = ${INSTALL}
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_SCRIPT = ${INSTALL}
INSTALL_HEADER = $(INSTALL_DATA)
transform = s,x,x,
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
host_alias = @host_alias@
host_triplet = alphaev68-dec-osf5.1
AMTAR = ${SHELL} /nfs/team71/psg/jkb/tmp/staden/src/io_lib/missing --run tar
AS = @AS@
AWK = gawk
CC = gcc
DEPDIR = .deps
DLLTOOL = @DLLTOOL@
ECHO = print -r
EXEEXT = 
INSTALL_STRIP_PROGRAM = ${SHELL} $(install_sh) -c -s
LIBM = -lm
LIBTOOL = $(SHELL) $(top_builddir)/libtool
LIBZ = -lz
LN_S = ln -s
OBJDUMP = @OBJDUMP@
OBJEXT = o
PACKAGE = io_lib
RANLIB = ranlib
STRIP = strip
VERSION = 1.8.11
am__include = include
am__quote = 
install_sh = /nfs/team71/psg/jkb/tmp/staden/src/io_lib/install-sh

bin_PROGRAMS = convert_trace makeSCF extract_seq index_tar scf_dump scf_info scf_update get_comment

convert_trace_SOURCES = convert_trace.c
convert_trace_LDADD = $(top_builddir)/read/libread.la

get_comment_SOURCES = get_comment.c
get_comment_LDADD = $(top_builddir)/read/libread.la

makeSCF_SOURCES = makeSCF.c
makeSCF_LDADD = $(top_builddir)/read/libread.la

extract_seq_SOURCES = extract_seq.c
extract_seq_LDADD = $(top_builddir)/read/libread.la

index_tar_SOURCES = index_tar.c

scf_dump_SOURCES = scf_dump.c
scf_dump_LDADD = $(top_builddir)/read/libread.la

scf_info_SOURCES = scf_info.c
scf_info_LDADD = $(top_builddir)/read/libread.la

scf_update_SOURCES = scf_update.c
scf_update_LDADD = $(top_builddir)/read/libread.la

INCLUDES = \
	-I${top_srcdir} \
	-I${top_srcdir}/include \
	-I${top_srcdir}/read \
	-I${top_srcdir}/alf \
	-I${top_srcdir}/abi \
	-I${top_srcdir}/ctf \
	-I${top_srcdir}/ztr \
	-I${top_srcdir}/plain \
	-I${top_srcdir}/scf \
	-I${top_srcdir}/exp_file \
	-I${top_srcdir}/utils

subdir = progs
mkinstalldirs = $(SHELL) $(top_srcdir)/mkinstalldirs
CONFIG_HEADER = $(top_builddir)/config.h
CONFIG_CLEAN_FILES =
bin_PROGRAMS = convert_trace$(EXEEXT) makeSCF$(EXEEXT) \
	extract_seq$(EXEEXT) index_tar$(EXEEXT) scf_dump$(EXEEXT) \
	scf_info$(EXEEXT) scf_update$(EXEEXT) get_comment$(EXEEXT)
PROGRAMS = $(bin_PROGRAMS)

am_convert_trace_OBJECTS = convert_trace.$(OBJEXT)
convert_trace_OBJECTS = $(am_convert_trace_OBJECTS)
convert_trace_DEPENDENCIES = $(top_builddir)/read/libread.la
convert_trace_LDFLAGS =
am_extract_seq_OBJECTS = extract_seq.$(OBJEXT)
extract_seq_OBJECTS = $(am_extract_seq_OBJECTS)
extract_seq_DEPENDENCIES = $(top_builddir)/read/libread.la
extract_seq_LDFLAGS =
am_get_comment_OBJECTS = get_comment.$(OBJEXT)
get_comment_OBJECTS = $(am_get_comment_OBJECTS)
get_comment_DEPENDENCIES = $(top_builddir)/read/libread.la
get_comment_LDFLAGS =
am_index_tar_OBJECTS = index_tar.$(OBJEXT)
index_tar_OBJECTS = $(am_index_tar_OBJECTS)
index_tar_LDADD = $(LDADD)
index_tar_DEPENDENCIES =
index_tar_LDFLAGS =
am_makeSCF_OBJECTS = makeSCF.$(OBJEXT)
makeSCF_OBJECTS = $(am_makeSCF_OBJECTS)
makeSCF_DEPENDENCIES = $(top_builddir)/read/libread.la
makeSCF_LDFLAGS =
am_scf_dump_OBJECTS = scf_dump.$(OBJEXT)
scf_dump_OBJECTS = $(am_scf_dump_OBJECTS)
scf_dump_DEPENDENCIES = $(top_builddir)/read/libread.la
scf_dump_LDFLAGS =
am_scf_info_OBJECTS = scf_info.$(OBJEXT)
scf_info_OBJECTS = $(am_scf_info_OBJECTS)
scf_info_DEPENDENCIES = $(top_builddir)/read/libread.la
scf_info_LDFLAGS =
am_scf_update_OBJECTS = scf_update.$(OBJEXT)
scf_update_OBJECTS = $(am_scf_update_OBJECTS)
scf_update_DEPENDENCIES = $(top_builddir)/read/libread.la
scf_update_LDFLAGS =

DEFS = -DHAVE_CONFIG_H
DEFAULT_INCLUDES =  -I. -I$(srcdir) -I$(top_builddir)
CPPFLAGS =  -I/usr/local/include
LDFLAGS = 
LIBS = 
depcomp = $(SHELL) $(top_srcdir)/depcomp
DEP_FILES = $(DEPDIR)/convert_trace.Po \
	$(DEPDIR)/extract_seq.Po $(DEPDIR)/get_comment.Po \
	$(DEPDIR)/index_tar.Po $(DEPDIR)/makeSCF.Po \
	$(DEPDIR)/scf_dump.Po $(DEPDIR)/scf_info.Po \
	$(DEPDIR)/scf_update.Po
COMPILE = $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) \
	$(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
LTCOMPILE = $(LIBTOOL) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) \
	$(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
CCLD = $(CC)
LINK = $(LIBTOOL) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) \
	$(AM_LDFLAGS) $(LDFLAGS) -o $@
CFLAGS = -g -O2
DIST_SOURCES = $(convert_trace_SOURCES) $(extract_seq_SOURCES) \
	$(get_comment_SOURCES) $(index_tar_SOURCES) $(makeSCF_SOURCES) \
	$(scf_dump_SOURCES) $(scf_info_SOURCES) $(scf_update_SOURCES)
DIST_COMMON = Makefile.am Makefile.in
SOURCES = $(convert_trace_SOURCES) $(extract_seq_SOURCES) $(get_comment_SOURCES) $(index_tar_SOURCES) $(makeSCF_SOURCES) $(scf_dump_SOURCES) $(scf_info_SOURCES) $(scf_update_SOURCES)

all: all-am

.SUFFIXES:
.SUFFIXES: .c .lo .o .obj

mostlyclean-libtool:
	-rm -f *.lo

clean-libtool:
	-rm -rf .libs _libs

distclean-libtool:
	-rm -f libtool
$(srcdir)/Makefile.in:  Makefile.am  $(top_srcdir)/configure.in $(ACLOCAL_M4)
	cd $(top_srcdir) && \
	  $(AUTOMAKE) --gnu  progs/Makefile
Makefile:  $(srcdir)/Makefile.in  $(top_builddir)/config.status
	cd $(top_builddir) && \
	  CONFIG_HEADERS= CONFIG_LINKS= \
	  CONFIG_FILES=$(subdir)/$@ $(SHELL) ./config.status
install-binPROGRAMS: $(bin_PROGRAMS)
	@$(NORMAL_INSTALL)
	$(mkinstalldirs) $(DESTDIR)$(bindir)
	@list='$(bin_PROGRAMS)'; for p in $$list; do \
	  p1=`echo $$p|sed 's/$(EXEEXT)$$//'`; \
	  if test -f $$p \
	     || test -f $$p1 \
	  ; then \
	    f=`echo $$p1|sed '$(transform);s/$$/$(EXEEXT)/'`; \
	   echo " $(INSTALL_PROGRAM_ENV) $(LIBTOOL) --mode=install $(INSTALL_PROGRAM) $$p $(DESTDIR)$(bindir)/$$f"; \
	   $(INSTALL_PROGRAM_ENV) $(LIBTOOL) --mode=install $(INSTALL_PROGRAM) $$p $(DESTDIR)$(bindir)/$$f; \
	  else :; fi; \
	done

uninstall-binPROGRAMS:
	@$(NORMAL_UNINSTALL)
	@list='$(bin_PROGRAMS)'; for p in $$list; do \
	  f=`echo $$p|sed 's/$(EXEEXT)$$//;$(transform);s/$$/$(EXEEXT)/'`; \
	  echo " rm -f $(DESTDIR)$(bindir)/$$f"; \
	  rm -f $(DESTDIR)$(bindir)/$$f; \
	done

clean-binPROGRAMS:
	-test -z "$(bin_PROGRAMS)" || rm -f $(bin_PROGRAMS)
convert_trace$(EXEEXT): $(convert_trace_OBJECTS) $(convert_trace_DEPENDENCIES) 
	@rm -f convert_trace$(EXEEXT)
	$(LINK) $(convert_trace_LDFLAGS) $(convert_trace_OBJECTS) $(convert_trace_LDADD) $(LIBS)
extract_seq$(EXEEXT): $(extract_seq_OBJECTS) $(extract_seq_DEPENDENCIES) 
	@rm -f extract_seq$(EXEEXT)
	$(LINK) $(extract_seq_LDFLAGS) $(extract_seq_OBJECTS) $(extract_seq_LDADD) $(LIBS)
get_comment$(EXEEXT): $(get_comment_OBJECTS) $(get_comment_DEPENDENCIES) 
	@rm -f get_comment$(EXEEXT)
	$(LINK) $(get_comment_LDFLAGS) $(get_comment_OBJECTS) $(get_comment_LDADD) $(LIBS)
index_tar$(EXEEXT): $(index_tar_OBJECTS) $(index_tar_DEPENDENCIES) 
	@rm -f index_tar$(EXEEXT)
	$(LINK) $(index_tar_LDFLAGS) $(index_tar_OBJECTS) $(index_tar_LDADD) $(LIBS)
makeSCF$(EXEEXT): $(makeSCF_OBJECTS) $(makeSCF_DEPENDENCIES) 
	@rm -f makeSCF$(EXEEXT)
	$(LINK) $(makeSCF_LDFLAGS) $(makeSCF_OBJECTS) $(makeSCF_LDADD) $(LIBS)
scf_dump$(EXEEXT): $(scf_dump_OBJECTS) $(scf_dump_DEPENDENCIES) 
	@rm -f scf_dump$(EXEEXT)
	$(LINK) $(scf_dump_LDFLAGS) $(scf_dump_OBJECTS) $(scf_dump_LDADD) $(LIBS)
scf_info$(EXEEXT): $(scf_info_OBJECTS) $(scf_info_DEPENDENCIES) 
	@rm -f scf_info$(EXEEXT)
	$(LINK) $(scf_info_LDFLAGS) $(scf_info_OBJECTS) $(scf_info_LDADD) $(LIBS)
scf_update$(EXEEXT): $(scf_update_OBJECTS) $(scf_update_DEPENDENCIES) 
	@rm -f scf_update$(EXEEXT)
	$(LINK) $(scf_update_LDFLAGS) $(scf_update_OBJECTS) $(scf_update_LDADD) $(LIBS)

mostlyclean-compile:
	-rm -f *.$(OBJEXT) core *.core

distclean-compile:
	-rm -f *.tab.c

include $(DEPDIR)/convert_trace.Po
include $(DEPDIR)/extract_seq.Po
include $(DEPDIR)/get_comment.Po
include $(DEPDIR)/index_tar.Po
include $(DEPDIR)/makeSCF.Po
include $(DEPDIR)/scf_dump.Po
include $(DEPDIR)/scf_info.Po
include $(DEPDIR)/scf_update.Po

distclean-depend:
	-rm -rf $(DEPDIR)

.c.o:
	source='$<' object='$@' libtool=no \
	depfile='$(DEPDIR)/$*.Po' tmpdepfile='$(DEPDIR)/$*.TPo' \
	$(CCDEPMODE) $(depcomp) \
	$(COMPILE) -c `test -f $< || echo '$(srcdir)/'`$<

.c.obj:
	source='$<' object='$@' libtool=no \
	depfile='$(DEPDIR)/$*.Po' tmpdepfile='$(DEPDIR)/$*.TPo' \
	$(CCDEPMODE) $(depcomp) \
	$(COMPILE) -c `cygpath -w $<`

.c.lo:
	source='$<' object='$@' libtool=yes \
	depfile='$(DEPDIR)/$*.Plo' tmpdepfile='$(DEPDIR)/$*.TPlo' \
	$(CCDEPMODE) $(depcomp) \
	$(LTCOMPILE) -c -o $@ `test -f $< || echo '$(srcdir)/'`$<
CCDEPMODE = depmode=gcc3
uninstall-info-am:

tags: TAGS

ID: $(HEADERS) $(SOURCES) $(LISP) $(TAGS_FILES)
	list='$(SOURCES) $(HEADERS) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	mkid -fID $$unique $(LISP)

TAGS:  $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	tags=; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	test -z "$(ETAGS_ARGS)$$unique$(LISP)$$tags" \
	  || etags $(ETAGS_ARGS) $$tags  $$unique $(LISP)

GTAGS:
	here=`CDPATH=: && cd $(top_builddir) && pwd` \
	  && cd $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) $$here

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH

DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)

top_distdir = ..
distdir = $(top_distdir)/$(PACKAGE)-$(VERSION)

distdir: $(DISTFILES)
	@for file in $(DISTFILES); do \
	  if test -f $$file; then d=.; else d=$(srcdir); fi; \
	  dir=`echo "$$file" | sed -e 's,/[^/]*$$,,'`; \
	  if test "$$dir" != "$$file" && test "$$dir" != "."; then \
	    $(mkinstalldirs) "$(distdir)/$$dir"; \
	  fi; \
	  if test -d $$d/$$file; then \
	    cp -pR $$d/$$file $(distdir) \
	    || exit 1; \
	  else \
	    test -f $(distdir)/$$file \
	    || cp -p $$d/$$file $(distdir)/$$file \
	    || exit 1; \
	  fi; \
	done
check-am: all-am
check: check-am
all-am: Makefile $(PROGRAMS)

installdirs:
	$(mkinstalldirs) $(DESTDIR)$(bindir)

install: install-am
install-exec: install-exec-am
install-data: install-data-am
uninstall: uninstall-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-am
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	  `test -z '$(STRIP)' || \
	    echo "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'"` install
mostlyclean-generic:

clean-generic:

distclean-generic:
	-rm -f Makefile $(CONFIG_CLEAN_FILES) stamp-h stamp-h[0-9]*

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
clean: clean-am

clean-am: clean-binPROGRAMS clean-generic clean-libtool mostlyclean-am

distclean: distclean-am

distclean-am: clean-am distclean-compile distclean-depend \
	distclean-generic distclean-libtool distclean-tags

dvi: dvi-am

dvi-am:

info: info-am

info-am:

install-data-am:

install-exec-am: install-binPROGRAMS

install-info: install-info-am

install-man:

installcheck-am:

maintainer-clean: maintainer-clean-am

maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-am

mostlyclean-am: mostlyclean-compile mostlyclean-generic \
	mostlyclean-libtool

uninstall-am: uninstall-binPROGRAMS uninstall-info-am

.PHONY: GTAGS all all-am check check-am clean clean-binPROGRAMS \
	clean-generic clean-libtool distclean distclean-compile \
	distclean-depend distclean-generic distclean-libtool \
	distclean-tags distdir dvi dvi-am info info-am install \
	install-am install-binPROGRAMS install-data install-data-am \
	install-exec install-exec-am install-info install-info-am \
	install-man install-strip installcheck installcheck-am \
	installdirs maintainer-clean maintainer-clean-generic \
	mostlyclean mostlyclean-compile mostlyclean-generic \
	mostlyclean-libtool tags uninstall uninstall-am \
	uninstall-binPROGRAMS uninstall-info-am

# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
