    {TK_CONFIG_INT, "-width", "width", "Width",
	 DEF_SHEET_WIDTH, offset(sw.columns), 0, NULL},
    {TK_CONFIG_INT, "-height", "height", "Height",
	 DEF_SHEET_HEIGHT, offset(sw.rows), 0, NULL},
    {TK_CONFIG_INT, "-hollow_cursor", "hollowCursor", "HollowCursor",
	 DEF_SHEET_HEIGHT, offset(sw.hollow_cursor), 0, NULL},
    {TK_CONFIG_FONT,
	 "-font",	"font",		"Font",		DEF_SHEET_FONT,
	 offset(sw.font),		0, NULL},
    {TK_CONFIG_FONT,
	 "-bold_font",	"boldFont",	"BoldFont",	DEF_SHEETB_FONT,
	 offset(sw.bold_font),		0, NULL},
    {TK_CONFIG_PIXELS,
	 "-borderWidth","borderWidth",	"BorderWidth",	"0.5m",
	 offset(sw.border_width),	0, NULL},
    {TK_CONFIG_BORDER,
	 "-background",	"background",	"Background",	NORMAL_BG,
	 offset(border),		TK_CONFIG_COLOR_ONLY, NULL},
    {TK_CONFIG_BORDER,
	 "-background",	"background",	"Background",	"white",
	 offset(border),		TK_CONFIG_MONO_ONLY, NULL},
    {TK_CONFIG_COLOR,
	 "-foreground",	"foreground",	"Foreground",	"#b03060",
	 offset(fg),			TK_CONFIG_COLOR_ONLY, NULL},
    {TK_CONFIG_COLOR,
	 "-foreground",	"foreground",	"Foreground",	"black",
	 offset(fg),			TK_CONFIG_MONO_ONLY, NULL},
    {TK_CONFIG_COLOR,
	 "-lightcolour", "lightcolour", "Foreground",  "gray70",
	 offset(light),			0, NULL},
    {TK_CONFIG_COLOR,
	 "-indelcolour", "indelcolour", "Foreground",  "red",
	 offset(indel_fg),			0, NULL},
    {TK_CONFIG_RELIEF,
	 "-relief",	"relief",	"Relief",	"flat",
	 offset(relief),		0, NULL},
    {TK_CONFIG_SYNONYM,
	 "-bg",		"background",	(char *)NULL,	(char *)NULL,
	 0,				0, NULL},
    {TK_CONFIG_SYNONYM,
	 "-fg",		"foreground",	(char *)NULL,	(char *)NULL,
	 0,				0, NULL},
    {TK_CONFIG_SYNONYM,
	 "-bd",		"borderWidth",	(char *)NULL,	(char *)NULL,
	 0,				0, NULL},
