\input epsf     % -*-texinfo-*-
\input texinfo
@c %**start of header
@setfilename gap5.info
@setcontentsaftertitlepage
@setshortcontentsaftertitlepage
@settitle Gap5
@setchapternewpage odd
@iftex
@afourpaper
@end iftex
@setchapternewpage odd
@c %**end of header

define(`__prog__',`gap5')
define(`__Prog__',`Gap5')

@set standalone
include(header.m4)

@titlepage
@title Gap5
@subtitle 
@author James Bonfield, Wellcome Trust Sanger Institute
@page
@vskip 0pt plus 1filll
_include(copyright.texi)
@end titlepage

@node Top
@ifinfo
@top top-gap5
@end ifinfo

_include(gap5-t.texi)

_split()
@node Index
@unnumbered Index
@printindex cp

@shortcontents
@contents
@bye
