\input epsf     % -*-texinfo-*-
\input texinfo
@c %**start of header
@setfilename manpages.info
@settitle Manual Pages
@setchapternewpage odd
@iftex
@afourpaper
@end iftex
@setchapternewpage odd
@c %**end of header

@set standalone
include(header.m4)

@titlepage
@title Manual Pages
@subtitle 
@author 
@page
@vskip 0pt plus 1filll
_include(copyright.texi)
@end titlepage

@node Top
@ifinfo
@top top-manpages
@end ifinfo

@raisesections
_include(manpages-t.texi)

_split()
@node Index
@unnumbered Index
@printindex cp
@lowersections

@shortcontents
@contents
@bye
