@lowersections

@c Put man pages in alphabetical order as there's little other sensible
@c ordering to these.

@page
@node Man-convert_trace
@chapter Convert_trace
_include(convert_trace.1.texi)

@page
@node Man-copy_db
@chapter Copy_db
_include(copy_db.1.texi)

@page
@node Man-copy_reads
@chapter Copy_reads
_include(copy_reads.1.texi)

@page
@node Man-eba
@chapter Eba
_include(eba.1.texi)

@page
@node Man-extract_seq
@chapter Extract_seq
_include(extract_seq.1.texi)

@page
@node Man-extract_fastq
@chapter Extract_fastq
_include(extract_fastq.1.texi)

@page
@node Man-find_renz
@chapter Find_renz
_include(find_renz.1.texi)

@page
@node Man-getABIfield
@chapter GetABIfield
_include(getABIfield.1.texi)

@page
@node Man-get_comment
@chapter Get_comment
_include(get_comment.1.texi)

@page
@node Man-get_scf_field
@chapter Get_scf_field
_include(get_scf_field.1.texi)

@page
@node Man-hash_exp
@chapter Hash_exp
_include(hash_exp.1.texi)

@page
@page
@node Man-hash_extract
@chapter Hash_extract
_include(hash_extract.1.texi)

@page
@node Man-hash_list
@chapter Hash_list
_include(hash_list.1.texi)

@node Man-hash_tar
@chapter Hash_tar
_include(hash_tar.1.texi)

@page
@node Man-init_tar
@chapter Init_tar
_include(init_tar.1.texi)

@page
@node Man-makeSCF
@chapter MakeSCF
_include(makeSCF.1.texi)

@page
@node Man-make_weights
@chapter Make_weights
_include(make_weights.1.texi)

@page
@node Man-polyA_clip
@chapter PolyA_clip
_include(polyA_clip.1.texi)

@node Man-qclip
@chapter Qclip
_include(qclip.1.texi)

@page
@node Man-screen_seq
@chapter Screen_seq
_include(screen_seq.1.texi)

@page
@node Man-tracediff
@chapter TraceDiff
_include(tracediff.1.texi)

@page
@node Man-trace_dump
@chapter Trace_dump
_include(trace_dump.1.texi)

@page
@node Man-vector_clip
@chapter Vector_clip
_include(vector_clip.1.texi)

@raisesections
